* Hyperland

** Install

#+BEGIN_SRC bash
  doas pacman --sync --refresh hyprland dunst qt6-wayland

  #
  # Optional, just for my case
  #
  doas pacman --sync --refresh alacritty tmux xclip
#+END_SRC


** How to run

#+BEGIN_SRC bash
  Hyperland
#+END_SRC

One tricky thing: If you run =tmux= before =Hyperland=, then =hyprctl= command will show the following errors:

#+BEGIN_SRC bash
  HYPRLAND_INSTANCE_SIGNATURE was not set! (Is Hyprland running?)
#+END_SRC

If you see that, killall =tmux=, exit current =Hyperland= and re-run it again to solve the problem.


** Configuration

The default configuration is: =~/.config/hypr/hyprland.conf=

*** Monitor resolution

#+BEGIN_SRC bash
  #
  # See https://wiki.hyprland.org/Configuring/Monitors/
  #
  # Syntax:
  #     monitor=name,resolution,position,scale
  #
  # monitor=,preferred,auto,auto
  #
  #
  monitor=HDMI1,2560x2880@60,0x0,1
#+END_SRC


*** Caplock -> Escape

You can find all supported settings in =/usr/share/X11/xkb/rules/base.lst=

#+BEGIN_SRC bash
  input {
      kb_layout = us
      kb_options = caps:escape
  }
#+END_SRC


*** Bindings

**** Set the MOD key

#+BEGIN_SRC bash
  $mainMod = SUPER
#+END_SRC


**** Bind key to command

#+BEGIN_SRC bash
  #
  # Syntax:
  #     bind=MODS,key,dispatcher,params
  #
  bind = $mainMod, RETURN, exec, alacritty
  bind = $mainMod, B, exec, GDK_DPI_SCALE=1.2 dbus-run-session brave > ~/temp/launch_brave_browser.log
  bind = $mainMod, Q, killactive, 
  # bind = $mainMod, M, exit, 
  bind = $mainMod, E, exec, emacs
  bind = $mainMod  CTRL, F, togglefloating, 
  bind = $mainMod, F, fullscreen
#+END_SRC


**** Move focus applicatiojn to different workspaces

#+BEGIN_SRC bash
  bind = $mainMod SHIFT, h, movefocus, l
  bind = $mainMod SHIFT, l, movefocus, r
  bind = $mainMod SHIFT, k, movefocus, u
  bind = $mainMod SHIFT, , movefocus, d
#+END_SRC


**** Switch workspace

#+BEGIN_SRC bash
  bind = $mainMod, 1, workspace, 1
  bind = $mainMod, 2, workspace, 2
  bind = $mainMod, 3, workspace, 3
  bind = $mainMod, 4, workspace, 4
  bind = $mainMod, 5, workspace, 5
  bind = $mainMod, 6, workspace, 6
  bind = $mainMod, 7, workspace, 7
  bind = $mainMod, 8, workspace, 8
  bind = $mainMod, 9, workspace, 9
  bind = $mainMod, 0, workspace, 10
#+END_SRC


** =hyprctl=

| Command              | Description                                                                                  |
|----------------------+----------------------------------------------------------------------------------------------|
| ~version~              | prints the hyprland version, meaning flags, commit and branch of build.                      |
| ~monitors~             | lists active outputs with their properties, 'monitors all' lists active and inactive outputs |
| ~workspaces~           | lists all workspaces with their properties                                                   |
| ~activeworkspace~      | gets the active workspace and its properties                                                 |
| ~workspacerules~       | gets the list of defined workspace rules                                                     |
| ~clients~              | lists all windows with their properties                                                      |
| ~devices~              | lists all connected keyboards and mice                                                       |
| ~decorations [window]~ | lists all decorations and their info                                                         |
| ~binds~                | lists all registered binds                                                                   |
| ~activewindow~         | gets the active window name and its properties                                               |
| ~layers~               | lists all the layers                                                                         |
| ~splash~               | prints the current random splash                                                             |
| ~getoption [option]~   | gets the config option status (values)                                                       |
| ~cursorpos~            | gets the current cursor pos in global layout coordinates                                     |
| ~animations~           | gets the current config'd info about animations and beziers                                  |
| ~instances~            | lists all running instances of hyprland with their info                                      |
| ~layouts~              | lists all layouts available (including plugin'd ones)                                        |
|                      |                                                                                              |

More examples from [[https://wiki.hyprland.org/Configuring/Using-hyprctl/][here]]


*** How to exit Hyprland

Make sure you exit =tmux= before doing that!!!
Make sure you exit =tmux= before doing that!!!
Make sure you exit =tmux= before doing that!!!

#+BEGIN_SRC bash
  hyprctl dispatch exit
#+END_SRC


*** List all monitors

#+BEGIN_SRC bash
  hyprctl monitors all

  # Monitor HDMI-A-1 (ID 0):
  #       3840x2160@60.00000 at 0x0
  #       description: LG Electronics LG HDR 4K 0x0003B9F0 (HDMI-A-1)
  #       make: LG Electronics
  #       model: LG HDR 4K
  #       serial: 0x0003B9F0
  #       active workspace: 1 (1)
  #       special workspace: 0 ()
  #       reserved: 0 0 0 0
  #       scale: 1.50
  #       transform: 0
  #       focused: yes
  #       dpmsStatus: 1
  #       vrr: 0
  #       activelyTearing: false
#+END_SRC


*** List all bindings

#+BEGIN_SRC bash
  hyprctl binds
#+END_SRC


*** Force to reload configuration

#+BEGIN_SRC bash
 hyprctl reload 
#+END_SRC


*** Apply settings dynamically

Use ~hyprctl keyword~ to apply settings dynamically.


#+BEGIN_SRC bash
  #
  # For example, temporary set 'SUPER + U' to fullscreen
  #
  hyprctl keyword bind SUPER, U, fullscreen 

  #
  # For example, temporary set monitor resolution
  #
  hyprctl keyword monitor HDMI1,2560x2880@60,0x0,1
#+END_SRC


*** Send notification

~hyprctl notify [ICON] [TIME_MS] [COLOR] [MESSAGE]~


- Icon options

  | Integer value | Description |
  |---------------+-------------|
  | ~-1~            | No ICONS    |
  | ~0~             | WARNING     |
  | ~1~             | INFO        |
  | ~2~             | HINT        |
  | ~3~             | ERROR       |
  | ~4~             | CONFUSED    |
  | ~5~             | OK          |
 
 
 

#+BEGIN_SRC bash
  # OK category
  hyprctl notify 0 5000 "rgb(FF9F1C)" " Network is down."
  hyprctl notify 1 5000 "rgb(ACE6FE)" " Email sent."
  hyprctl notify 3 5000 "rgb(f44747)" " Task failed."
  hyprctl notify 5 5000 "rgb(6fc3df)" " Email sent."
#+END_SRC


** Wallpaper

*** =swww= - wallpaper backend

**** Install

#+BEGIN_SRC bash
  paru --sync --refresh swww
#+END_SRC

Make sure to select =swww= (default =1=) rather than the =swww-git= (outdated) and choose =rustup= (option =2=)!!!


**** How to set wallpaper

#+BEGIN_SRC bash
  #
  # Init once
  #
  swww init

  #
  # Set wallpaper
  #
  swww img YOUR_WALLPAPER_FILENAME_HERE

  #
  # Apply transition when changing wallpaper
  #
  www img --transition-type wipe --transition-angle 45 ~/Photos/wallpaper/digit-city-3.jpg
#+END_SRC


**** In Hyperland configuration 

#+BEGIN_SRC bash
  exec-once = swww init && swww img YOUR_WALLPAPER_FILENAME_HERE
#+END_SRC


*** =waypaper= (GUI - frontend)

**** Install

#+BEGIN_SRC bash
  paru --sync --search waypaper

#+END_SRC


**** how to run

#+BEGIN_SRC bash
  #
  # Run with given backend, you only need to pass for the first time
  # and then 'waypaper' will keep using it
  #
  waypaper --backend swww
#+END_SRC

You might get the following error when choosing a wallpaper : =No such file or directory: swaybg=

That's you got a wrong settings in =~/.config/waypaper/config.ini=, open and fix it like below:

Pay attention to the =backend= setting!!!

#+BEGIN_SRC bash
  cat ~/.config/waypaper/config.ini

  # [Settings]
  # folder = /home/wison/Photos/wallpaper
  # fill = Fill
  # sort = name
  # backend = swww
  # color = #FFFFFF
  # language = en
  # subfolders = False
  # wallpaper = /home/wison/Photos/wallpaper/forest.jpg
  # monitors = All
#+END_SRC


**** In Hyperland configuration 

#+BEGIN_SRC bash
  #
  # Reset to the last chosen wallpaper
  #
  exec-once = waypaper --restore
#+END_SRC


** Waybar

*** Install

#+BEGIN_SRC bash
  doas pacman --sync --refresh waybar
#+END_SRC


*** Configuration

The default configuration is: =~/.config/waybar/config.conf=

The default style configuration is: =~/.config/waybar/style.css=


*** In Hyperland configuration 

#+BEGIN_SRC bash
  exec-once = waybar
#+END_SRC


** Screen sharing

Install guide is [[https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580][here]].


*** Install

DO NOT install another =xdg-desktop-portal-hyprland= version from =pacman=!!!
DO NOT install another =xdg-desktop-portal-hyprland= version from =pacman=!!!
DO NOT install another =xdg-desktop-portal-hyprland= version from =pacman=!!!

#+BEGIN_SRC bash
  #
  # Install dependencies
  #
  doas pacman --sync --refresh libinih qt6-base qt5-wayland qt6-wayland grim slurp

  #
  # Only install via AUR, it has extra functionality like `window sharing`
  #
  paru --sync --refresh xdg-desktop-portal-hyprland-git
#+END_SRC


*** Configuration

Add the following settings into =~./config/hypr/hyprland.conf=:

#+BEGIN_SRC bash
  exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#+END_SRC

This will make sure that =xdg-desktop-portal-hyprland= can get the required variables on startup.

Restart =Hyprland= to take affect.


*** Limitation

You only can share window (or particular app), you can't share the entire screen!!!


*** Troubeshooting

**** Make sure the following services are running

#+BEGIN_SRC bash
  systemctl --user status pipewire wireplumber 
  systemctl --user status xdg-desktop-portal-hyprland
#+END_SRC
